services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_DB=shareit
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://shareit:shareit@db:5432/shareit -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE TABLE IF NOT EXISTS public."users" (
          id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name  VARCHAR(255) NOT NULL,
          email VARCHAR(512) NOT NULL,
          CONSTRAINT pk_user PRIMARY KEY (id),
          CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
        );
        CREATE TABLE IF NOT EXISTS public."items" (
          id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name        VARCHAR(255) NOT NULL,
          description VARCHAR(512) NOT NULL,
          available   BOOLEAN      NOT NULL,
          owner_id    BIGINT       NOT NULL,
          request_id  BIGINT,
          CONSTRAINT pk_item PRIMARY KEY (id),
          CONSTRAINT USERS_FK FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE
        );
        CREATE TABLE IF NOT EXISTS public."bookings" (
          id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          start_date TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
          end_date   TIMESTAMP WITHOUT TIME ZONE  NOT NULL,
          item_id    BIGINT                       NOT NULL,
          booker_id  BIGINT                       NOT NULL,
          status     VARCHAR(25)                  NOT NULL,
          CONSTRAINT pk_booking PRIMARY KEY (id),
          CONSTRAINT USERS_FK2 FOREIGN KEY (BOOKER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
          CONSTRAINT ITEMS_FK FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID) ON DELETE CASCADE ON UPDATE CASCADE
        );
        CREATE TABLE IF NOT EXISTS public."comments" (
          id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          text      varchar(1024)               NOT NULL,
          item_id   BIGINT                      NOT NULL,
          author_id BIGINT                      NOT NULL,
          created   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
          CONSTRAINT pk_comment PRIMARY KEY (id),
          CONSTRAINT ITEMS_FK2 FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID) ON DELETE CASCADE,
          CONSTRAINT USERS_FK3 FOREIGN KEY (AUTHOR_ID) REFERENCES USERS(ID) ON DELETE CASCADE
        );
        ALTER USER shareit SET default_transaction_read_only = off;
        EOSQL