server:
  port: 9090

spring:
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        connection:
          read_only: false
    spring.sql.init.mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: shareit
    password: shareit

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: INFO
        transaction: INFO
        transaction.interceptor: INFO
